# Generated by Django 2.1.7 on 2019-08-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=10, verbose_name='Identificação')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('largura', models.PositiveIntegerField()),
                ('comprimento', models.PositiveIntegerField()),
                ('capacidadeAlojamento', models.PositiveIntegerField(verbose_name='Capacidade de Alojamento')),
                ('ventilacao', models.CharField(max_length=50, verbose_name='Tipo de ventilação')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataChegada', models.CharField(max_length=50)),
                ('peso', models.PositiveIntegerField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=2, unique=True)),
                ('loteMatriz', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo', max_length=100)),
                ('email', models.EmailField(help_text='Digite seu e-mail', max_length=100)),
                ('fone', models.CharField(help_text='Digite seu telefone', max_length=15, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Racao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4, unique=True)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='racao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Racao'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Estado'),
        ),
        migrations.AddField(
            model_name='aviario',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Cidade'),
        ),
    ]
